-- Ingredient vocabulary + role-aware substitution rules (CLAUDE.md §5.1).
-- concept_id values are the data teammate's real concept ids (data-science/concepts.parquet). A rule matches its
-- concept AND all descendants (tofu → tofu_dimljeni …), so point rules at the most specific concept that fits.
-- prefer = facet values exactly as in the catalog (products.atr_*); checked by `npm run validate:catalog`.
-- Re-runnable: npm run seed:knowledge

truncate substitution_rules, ingredients restart identity cascade;

insert into ingredients (slug, name_hr, aliases, is_vegan, category, grams_per_piece) values
  -- non-vegan: dairy
  ('mlijeko',            'mlijeko',               '{kravlje mlijeko,svježe mlijeko,trajno mlijeko,punomasno mlijeko}', false, 'mliječni', null),
  ('maslac',             'maslac',                '{putar,puter,maslaca}',                            false, 'mliječni', null),
  ('vrhnje_za_kuhanje',  'vrhnje za kuhanje',     '{kuhinjsko vrhnje}',                               false, 'mliječni', null),
  ('slatko_vrhnje',      'slatko vrhnje',         '{vrhnje za šlag,šlag,vrhnje za tučenje}',          false, 'mliječni', null),
  ('kiselo_vrhnje',      'kiselo vrhnje',         '{vrhnje,pavlaka,schmand}',                         false, 'mliječni', 180),
  ('mileram',            'mileram',               '{}',                                               false, 'mliječni', null),
  ('jogurt',             'jogurt',                '{tekući jogurt,grčki jogurt}',                     false, 'mliječni', null),
  ('sir',                'sir',                   '{tvrdi sir,polutvrdi sir,gauda,edamer,trapist,topljivi sir,ribani sir}', false, 'mliječni', null),
  ('parmezan',           'parmezan',              '{grana padano,pecorino}',                          false, 'mliječni', null),
  ('mozzarella',         'mozzarella',            '{mocarela}',                                       false, 'mliječni', 125),
  ('svjezi_sir',         'svježi sir',            '{kravlji sir,sir za štrukle,skuta,ricotta}',       false, 'mliječni', null),
  ('krem_sir',           'krem sir',              '{sirni namaz,philadelphia}',                       false, 'mliječni', null),
  ('mascarpone',         'mascarpone',            '{maskarpone}',                                     false, 'mliječni', null),
  -- eggs (one slug; the role says how it is used)
  ('jaje',               'jaje',                  '{jaja,jajce,žumanjak,žumanjci,bjelanjak,bjelanjci}', false, 'jaja', 55),
  -- meat and fish
  ('mljeveno_meso',      'mljeveno meso',         '{mljevena junetina,mljevena svinjetina,miješano mljeveno meso}', false, 'meso', null),
  ('meso_komadi',        'meso u komadima',       '{govedina,junetina,svinjetina,teletina,janjetina,meso za gulaš,svinjski vrat,but,goveđe meso}', false, 'meso', null),
  ('odrezak',            'odrezak',               '{šnicla,teleći odrezak,svinjski odrezak,teleći but za odreske}', false, 'meso', 150),
  ('piletina',           'piletina',              '{pileća prsa,pileći file,piletine,batak,pileće meso}', false, 'meso', null),
  ('panceta',            'panceta',               '{pancetta}',                                       false, 'meso', null),
  ('slanina',            'slanina',               '{špek,dimljena slanina,bacon}',                    false, 'meso', null),
  ('kobasica',           'kobasica',              '{kobasice,češnjovka,hrenovka,hrenovke}',           false, 'meso', 100),
  ('suho_meso',          'suho meso',             '{suha rebra,dimljeno meso,kare}',                  false, 'meso', null),
  ('sunka',              'šunka',                 '{pršut,narezak}',                                  false, 'meso', null),
  ('svinjska_mast',      'svinjska mast',         '{mast}',                                           false, 'masnoće', null),
  ('riba',               'riba',                  '{bijela riba,oslić,riblji file,miješana riba,škampi}', false, 'riba', null),
  ('tuna',               'tuna',                  '{tunjevina}',                                      false, 'riba', 80),
  ('temeljac_mesni',     'mesni temeljac',        '{goveđa kocka,pileća kocka,kokošja kocka,juneći temeljac,goveđi temeljac}', false, 'začini', 10),
  -- other non-vegan
  ('med',                'med',                   '{}',                                               false, 'zaslađivači', null),
  ('zelatina',           'želatina',              '{želatina u listićima}',                           false, 'ostalo', 10),
  ('majoneza',           'majoneza',              '{}',                                               false, 'umaci', null),
  ('mlijecna_cokolada',  'mliječna čokolada',     '{}',                                               false, 'slatkiši', null),
  ('tjestenina_s_jajima','tjestenina s jajima',   '{jajčana tjestenina,domaći rezanci}',              false, 'tjestenina', null),
  ('tijesto_za_lazanje', 'tijesto za lazanje',    '{kore za lazanje,lazanje listovi}',                false, 'tjestenina', null),
  ('keksi',              'keksi',                 '{keksi s maslacem,digestive,petit beurre,čajni keksi}', false, 'slatkiši', null),
  ('piskote',            'piškote',               '{savoiardi,biskvitni prsti}',                      false, 'slatkiši', 7),
  ('lisnato_tijesto',    'lisnato tijesto',       '{gotovo lisnato tijesto}',                         false, 'tijesto', 500),
  -- vegan basics (so the extractor has a full vocabulary)
  ('vegeta',             'Vegeta',                '{vegeta natur,dodatak jelima,vegeta maestro}',     true,  'začini', null),
  ('brasno',             'brašno',                '{glatko brašno,oštro brašno}',                     true,  'osnovno', null),
  ('secer',              'šećer',                 '{šećer u prahu,smeđi šećer}',                      true,  'osnovno', null),
  ('sol',                'sol',                   '{}',                                               true,  'začini', null),
  ('papar',              'papar',                 '{biber}',                                          true,  'začini', null),
  ('ulje',               'ulje',                  '{suncokretovo ulje,maslinovo ulje}',               true,  'masnoće', null),
  ('luk',                'luk',                   '{crveni luk,kapula}',                              true,  'povrće', 100),
  ('cesnjak',            'češnjak',               '{bijeli luk,češanj}',                              true,  'povrće', 5),
  ('krumpir',            'krumpir',               '{krompir}',                                        true,  'povrće', 150),
  ('riza',               'riža',                  '{pirinač}',                                        true,  'žitarice', null),
  ('kiselo_zelje',       'kiselo zelje',          '{kiseli kupus,listovi kiselog kupusa}',            true,  'povrće', null),
  ('rajcica',            'rajčica',               '{pasirana rajčica,koncentrat rajčice,paradajz,pelati}', true, 'povrće', 100),
  ('mrkva',              'mrkva',                 '{}',                                               true,  'povrće', 80),
  ('tjestenina',         'tjestenina',            '{špageti,makaroni,penne}',                         true,  'tjestenina', null),
  ('prasak_za_pecivo',   'prašak za pecivo',      '{}',                                               true,  'osnovno', 12),
  ('slatka_paprika',     'slatka paprika (začin)','{mljevena paprika}',                               true,  'začini', null),
  ('voda',               'voda',                  '{}',                                               true,  'osnovno', null),
  ('vanilin_secer',      'vanilin šećer',         '{}',                                               true,  'osnovno', 10);

insert into substitution_rules (ingredient_slug, role, concept_id, prefer, ratio, notes_hr, rank) values
  -- mlijeko
  ('mlijeko', 'any',   'napitak_zob',   '{"zasladeno":"nezaslađeno","okus":"bez okusa / natur"}', 1, 'Zobeni napitak bez šećera i okusa najbliži je mlijeku u slanim i slatkim jelima.', 1),
  ('mlijeko', 'any',   'napitak_soja',  '{"zasladeno":"nezaslađeno","okus":"bez okusa / natur"}', 1, 'Sojin napitak ima više bjelančevina, dobro veže tijesto i kreme.', 2),
  ('mlijeko', 'any',   'napitak_badem', '{"zasladeno":"nezaslađeno","okus":"bez okusa / natur"}', 1, 'Lagan okus; slabije veže, bolji za slatka jela.', 3),
  ('mlijeko', 'sweet', 'napitak_zob',   '{}',                       1, 'U kolačima smije biti i aromatiziran ili zaslađen napitak.', 1),
  ('mlijeko', 'sweet', 'napitak_badem', '{"okus":"vanilija"}',      1, 'Bademov napitak s vanilijom za kreme i deserte.', 2),
  -- maslac
  ('maslac', 'frying',  'biljno_ulje',       '{}', 0.8, 'Za prženje i pirjanje maslac nije potreban: dovoljno je ulje (oko 20 % manje).', 1),
  ('maslac', 'frying',  'ulje_suncokretovo', '{}', 0.8, 'Suncokretovo ulje neutralnog okusa.', 2),
  ('maslac', 'flavour', 'margarin',          '{}', 1,   'Kad je maslac nositelj okusa (pire, umaci, rižoto), biljni margarin 1:1.', 1),
  ('maslac', 'flavour', 'ulje_maslinovo',    '{}', 0.8, 'Maslinovo ulje kad okus maslaca nije presudan.', 2),
  ('maslac', 'baking',  'margarin',          '{}', 1,   'Za tijesta biljni margarin u bloku 1:1 zadržava strukturu.', 1),
  ('maslac', 'baking',  'ulje_kokosovo',     '{}', 0.8, 'Kokosovo ulje u tijestima, oko 20 % manje; blag okus kokosa.', 2),
  ('maslac', 'any',     'margarin',          '{}', 1,   'Biljni margarin 1:1.', 1),
  ('maslac', 'any',     'biljno_ulje',       '{}', 0.8, 'Ulje kad maslac služi samo kao masnoća.', 2),
  -- vrhnja i jogurt
  ('vrhnje_za_kuhanje', 'any',        'vrhnje_kuhanje',   '{}', 1, 'Biljno vrhnje za kuhanje ne zgrušava se na vatri.', 1),
  ('vrhnje_za_kuhanje', 'any',        'kokosovo_mlijeko', '{}', 1, 'Kokosovo mlijeko za curry i azijska jela.', 2),
  ('slatko_vrhnje',     'any',        'slag_biljni',      '{}', 1, 'Biljno vrhnje za šlag tuče se kao slatko vrhnje.', 1),
  ('slatko_vrhnje',     'any',        'kokosova_krema',   '{}', 1, 'Ohlađena kokosova krema može se istući u šlag.', 2),
  ('slatko_vrhnje',     'creaminess', 'vrhnje_kuhanje',   '{}', 1, 'U umacima i juhama biljno vrhnje za kuhanje.', 1),
  ('kiselo_vrhnje',     'any',        'kiselo_vrhnje_biljno', '{}', 1, 'Biljna alternativa kiselom vrhnju 1:1.', 1),
  ('kiselo_vrhnje',     'any',        'biljni_jogurt',    '{"okus":"bez okusa / natur"}', 1, 'Biljni jogurt natur s kapljicom limuna.', 2),
  ('mileram',           'any',        'kiselo_vrhnje_biljno', '{}', 1, 'Biljna alternativa kiselom vrhnju 1:1.', 1),
  ('mileram',           'any',        'biljni_jogurt',    '{"okus":"bez okusa / natur"}', 1, 'Biljni jogurt natur za lakšu varijantu.', 2),
  ('jogurt',            'any',        'biljni_jogurt',    '{"okus":"bez okusa / natur"}', 1, 'Biljni jogurt natur 1:1.', 1),
  ('jogurt',            'any',        'jogurt_kokos',     '{}', 1, 'Kokosov jogurt je gušći, dobar za kreme.', 2),
  -- sirevi
  ('sir',         'any', 'biljni_sir',      '{}',                   1,   'Biljni sir se topi slično kravljem.', 1),
  ('sir',         'any', 'sir_polutvrdi',   '{}',                   1,   'Biljni polutvrdi sir (gauda, cheddar) za narezivanje i topljenje.', 2),
  ('parmezan',    'any', 'sir_parmezan',    '{}',                   1,   'Biljni "parmezan" za ribanje.', 1),
  ('parmezan',    'any', 'biljni_sir',      '{"oblik":"ribano"}',   1,   'Ribani biljni sir za posipanje.', 2),
  ('mozzarella',  'any', 'sir_mozzarella',  '{}',                   1,   'Biljna mozzarella za pizzu i zapečena jela.', 1),
  ('mozzarella',  'any', 'biljni_sir',      '{"oblik":"ribano"}',   1,   'Ribani biljni sir koji se topi.', 2),
  ('svjezi_sir',  'any', 'tofu_natur',      '{}',                   1,   'Izmrvljeni tofu natur s malo biljnog jogurta i limuna ima teksturu svježeg sira.', 1),
  ('svjezi_sir',  'any', 'sir_svjezi',      '{}',                   1,   'Gotova biljna zamjena za svježi sir.', 2),
  ('svjezi_sir',  'any', 'biljni_jogurt',   '{"okus":"bez okusa / natur"}', 0.5, 'Za kremastiji nadjev dodaj biljni jogurt.', 3),
  ('krem_sir',    'any', 'sir_namaz',       '{}',                   1,   'Biljni sirni namaz kao krem sir.', 1),
  ('krem_sir',    'any', 'sir_kremasti',    '{}',                   1,   'Meki kremasti biljni sir.', 2),
  ('mascarpone',  'any', 'sir_mascarpone',  '{}',                   1,   'Biljni mascarpone za tiramisu 1:1.', 1),
  ('mascarpone',  'any', 'sir_kremasti',    '{}',                   1,   'Kremasti biljni sir, po želji s malo šlaga.', 2),
  -- jaja
  ('jaje', 'binder',     'laneno_sjeme',   '{"oblik":"mljeveno"}', 0.18, '1 jaje = 1 žlica mljevenog lana + 3 žlice vode, odstajati 5 min.', 1),
  ('jaje', 'binder',     'chia',           '{}',                   0.18, '1 jaje = 1 žlica chia sjemenki + 3 žlice vode, 10 min do gela. Veže, ali ne diže.', 2),
  ('jaje', 'binder',     'skrob_vezivo',   '{}',                   0.2,  'Škrob (gustin) veže kreme i nadjeve.', 3),
  ('jaje', 'leavening',  'prasak_pecivo',  '{}',                   0.05, 'Za dizanje: malo više praška za pecivo uz biljni napitak i ulje.', 1),
  ('jaje', 'leavening',  'laneno_sjeme',   '{"oblik":"mljeveno"}', 0.18, 'Lan veže, ali slabije diže; dodaj prašak za pecivo.', 2),
  ('jaje', 'base',       'tofu_natur',     '{}',                   1,    'Za kajganu i omlet: izmrvljeni tofu s kurkumom i crnom soli.', 1),
  ('jaje', 'base',       'brasno_slanutak','{}',                   0.5,  'Smjesa brašna od slanutka i vode peče se kao omlet.', 2),
  ('jaje', 'creaminess', 'skrob_vezivo',   '{}',                   0.2,  'U kremama (kremšnite, puding) jaja zamjenjuje škrob, kurkuma daje boju.', 1),
  ('jaje', 'creaminess', 'tofu_svileni',   '{}',                   1,    'Svileni tofu za kremaste, pečene kreme (cheesecake).', 2),
  ('jaje', 'sauce',      'tofu_svileni',   '{}',                   1,    'Za umak (carbonara): svileni tofu izmiksan s biljnim vrhnjem i crnom soli.', 1),
  ('jaje', 'sauce',      'vrhnje_kuhanje', '{}',                   1,    'Biljno vrhnje za kuhanje s kurkumom daje kremasti umak.', 2),
  ('jaje', 'glaze',      'napitak_soja',   '{"zasladeno":"nezaslađeno"}', 0.5, 'Za premaz: biljni napitak s kapljicom ulja (i malo šećera za sjaj).', 1),
  ('jaje', 'any',        'laneno_sjeme',   '{"oblik":"mljeveno"}', 0.18, '1 jaje = 1 žlica mljevenog lana + 3 žlice vode.', 1),
  ('jaje', 'any',        'chia',           '{}',                   0.18, '1 jaje = 1 žlica chia sjemenki + 3 žlice vode.', 2),
  -- meso i riba
  ('mljeveno_meso', 'any',   'mljeveno',          '{}',    1,    'Biljno mljeveno 1:1, ne treba ga dugo pirjati.', 1),
  ('mljeveno_meso', 'any',   'soja_teksturirana', '{}',    0.35, 'Suhi sojin granulat namočen u temeljcu: 100 g suhog ≈ 300 g mesa.', 2),
  ('mljeveno_meso', 'any',   'tempeh',            '{}',    1,    'Izmrvljeni tempeh za čvršću teksturu.', 3),
  ('meso_komadi',   'any',   'soja_komadi',       '{}',    0.35, 'Sojini komadi namočeni u temeljcu za gulaš i paprikaš: 100 g suhih ≈ 300 g mesa.', 1),
  ('meso_komadi',   'any',   'seitan',            '{}',    1,    'Seitan ima vlaknastu teksturu mesa i podnosi dugo kuhanje.', 2),
  ('meso_komadi',   'any',   'tempeh',            '{}',    1,    'Tempeh na kockice, prethodno zapržen.', 3),
  ('odrezak',       'any',   'odrezak',           '{}',    1,    'Gotovi biljni odresci za pohanje i pečenje.', 1),
  ('odrezak',       'any',   'seitan',            '{}',    1,    'Seitan narezan na ploške, istučen i pohan.', 2),
  ('odrezak',       'any',   'tofu_natur',        '{}',    1,    'Prešani tofu na ploške, mariniran i pohan.', 3),
  ('piletina',      'any',   'piletina',          '{}',    1,    'Biljni pileći komadi 1:1.', 1),
  ('piletina',      'any',   'tofu_natur',        '{}',    1,    'Tofu natur, prešan i mariniran.', 2),
  ('piletina',      'any',   'soja_komadi',       '{}',    0.35, 'Sojini komadi namočeni u temeljcu.', 3),
  ('panceta',       'any',   'tofu_dimljeni',     '{}',    1,    'Dimljeni tofu na kockice daje dimljeni okus pancete.', 1),
  ('panceta',       'any',   'seitan_dimljeni',   '{}',    1,    'Dimljeni seitan na kockice.', 2),
  ('slanina',       'any',   'tofu_dimljeni',     '{}',    1,    'Dimljeni tofu na tanke trakice, zapržen.', 1),
  ('slanina',       'any',   'slanina',           '{}',    1,    'Biljna slanina.', 2),
  ('suho_meso',     'any',   'tofu_dimljeni',     '{}',    1,    'Dimljeni tofu nosi dimljeni okus u varivima i sarmi.', 1),
  ('suho_meso',     'any',   'seitan_dimljeni',   '{}',    1,    'Dimljeni seitan u komadima.', 2),
  ('kobasica',      'any',   'kobasica',          '{}',    1,    'Veganske kobasice 1:1.', 1),
  ('kobasica',      'any',   'tofu_dimljeni',     '{}',    1,    'Dimljeni tofu u komadima.', 2),
  ('sunka',         'any',   'suhomesnato',       '{}',    1,    'Biljni narezak umjesto šunke ili pršuta.', 1),
  ('sunka',         'any',   'tofu_dimljeni',     '{}',    1,    'Dimljeni tofu narezan na tanko.', 2),
  ('svinjska_mast', 'any',   'biljno_ulje',       '{}',    0.9,  'Ulje umjesto masti za prženje i dinstanje.', 1),
  ('svinjska_mast', 'baking','margarin',          '{}',    1,    'Biljni margarin u bloku za tijesta.', 1),
  ('riba',          'any',   'tofu_natur',        '{}',    1,    'Čvrsti tofu u komadima, mariniran s limunom i algama.', 1),
  ('riba',          'any',   'nori',              '{}',    0.02, 'Malo nori alge daje okus mora.', 2),
  ('tuna',          'any',   'slanutak',          '{}',    1,    'Zgnječeni slanutak s malo nori alge oponaša tunu iz konzerve.', 1),
  ('tuna',          'any',   'nori',              '{}',    0.02, 'Nori alga za okus mora.', 2),
  ('temeljac_mesni','any',   'temeljac_povrtni',  '{}',    1,    'Povrtni temeljac ili kocka umjesto mesne.', 1),
  -- ostalo
  ('med',                'any', 'sirup_agava',     '{}',   1,    'Agavin sirup 1:1, malo je slađi.', 1),
  ('med',                'any', 'sirup_javor',     '{}',   1,    'Javorov sirup 1:1, s karamelnim okusom.', 2),
  ('zelatina',           'any', 'agar',            '{}',   0.25, 'Agar umjesto želatine: oko četvrtine količine, mora prokuhati.', 1),
  ('zelatina',           'any', 'pektin',          '{}',   0.5,  'Pektin za voćne kreme i želee.', 2),
  ('majoneza',           'any', 'majoneza',        '{}',   1,   'Veganska majoneza 1:1.', 1),
  ('mlijecna_cokolada',  'any', 'cokolada_tamna',  '{}',   1,   'Većina tamnih čokolada je bez mlijeka.', 1),
  ('mlijecna_cokolada',  'any', 'cokolada_kuhanje','{}',   1,   'Čokolada za kuhanje bez mlijeka.', 2),
  ('tjestenina_s_jajima','any', 'tjestenina',      '{}',   1,   'Većina suhe tjestenine (durum) je bez jaja.', 1),
  ('tijesto_za_lazanje', 'any', 'lazanje',         '{}',   1,   'Suhe kore za lazanje od durum pšenice su bez jaja.', 1),
  ('keksi',              'any', 'keks_cajni',      '{}',   1,   'Čajni keksi bez maslaca za podlogu torte.', 1),
  ('keksi',              'any', 'keks',            '{}',   1,   'Veganski keksi.', 2),
  ('piskote',            'any', 'keks_cajni',      '{}',   1,   'Veganske piškote rijetko se prodaju: čajni keksi natopljeni kavom.', 1),
  ('lisnato_tijesto',    'any', 'tijesto_lisnato', '{}',   1,   'Mnoga gotova lisnata tijesta rade se s biljnom masnoćom.', 1);
