-- Ingredient vocabulary + role-aware substitution rules (CLAUDE.md §5.1).
-- concept_id values must exist in the catalog: checked by `npm run validate:catalog`.
-- ⚠️ These concept ids match the MOCK catalog. When the real export arrives, remap them to the real concept ids.
-- Re-runnable: npm run seed:knowledge

truncate substitution_rules, ingredients restart identity cascade;

insert into ingredients (slug, name_hr, aliases, is_vegan, category, grams_per_piece) values
  -- non-vegan
  ('mlijeko',            'mlijeko',               '{kravlje mlijeko,svježe mlijeko,trajno mlijeko}', false, 'mliječni', null),
  ('maslac',             'maslac',                '{putar,puter,maslaca}',                            false, 'mliječni', null),
  ('vrhnje_za_kuhanje',  'vrhnje za kuhanje',     '{kuhinjsko vrhnje}',                               false, 'mliječni', null),
  ('slatko_vrhnje',      'slatko vrhnje',         '{vrhnje za šlag,šlag}',                            false, 'mliječni', null),
  ('kiselo_vrhnje',      'kiselo vrhnje',         '{vrhnje}',                                         false, 'mliječni', null),
  ('mileram',            'mileram',               '{}',                                               false, 'mliječni', null),
  ('jogurt',             'jogurt',                '{tekući jogurt,grčki jogurt}',                     false, 'mliječni', null),
  ('sir',                'sir',                   '{tvrdi sir,polutvrdi sir,gauda,edamer,trapist}',   false, 'mliječni', null),
  ('parmezan',           'parmezan',              '{grana padano,ribani sir}',                        false, 'mliječni', null),
  ('mozzarella',         'mozzarella',            '{mocarela}',                                       false, 'mliječni', null),
  ('svjezi_sir',         'svježi sir',            '{kravlji sir,sir za štrukle,skuta}',               false, 'mliječni', null),
  ('krem_sir',           'krem sir',              '{sirni namaz,philadelphia}',                       false, 'mliječni', null),
  ('jaje',               'jaje',                  '{jaja,jajce,žumanjak,bjelanjak}',                  false, 'jaja', 55),
  ('mljeveno_meso',      'mljeveno meso',         '{mljevena junetina,mljevena svinjetina,miješano mljeveno meso}', false, 'meso', null),
  ('panceta',            'panceta',               '{pancetta}',                                       false, 'meso', null),
  ('slanina',            'slanina',               '{špek,dimljena slanina,bacon}',                    false, 'meso', null),
  ('kobasica',           'kobasica',              '{kobasice,češnjovka,hrenovka,hrenovke}',           false, 'meso', 100),
  ('suho_meso',          'suho meso',             '{suha rebra,dimljeno meso,kare}',                  false, 'meso', null),
  ('sunka',              'šunka',                 '{pršut}',                                          false, 'meso', null),
  ('piletina',           'piletina',              '{pileća prsa,piletine,batak}',                     false, 'meso', null),
  ('svinjska_mast',      'svinjska mast',         '{mast}',                                           false, 'masnoće', null),
  ('med',                'med',                   '{}',                                               false, 'zaslađivači', null),
  ('tjestenina_s_jajima','tjestenina s jajima',   '{jajčana tjestenina,domaći rezanci}',              false, 'tjestenina', null),
  ('majoneza',           'majoneza',              '{}',                                               false, 'umaci', null),
  ('zelatina',           'želatina',              '{}',                                               false, 'ostalo', null),
  ('tuna',               'tuna',                  '{tunjevina}',                                      false, 'riba', null),
  ('mlijecna_cokolada',  'mliječna čokolada',     '{}',                                               false, 'slatkiši', null),
  ('temeljac_mesni',     'mesni temeljac',        '{goveđa kocka,pileća kocka,juneći temeljac}',      false, 'začini', null),
  -- vegan basics (so the extractor has a full vocabulary)
  ('brasno',             'brašno',                '{glatko brašno,oštro brašno}',                     true,  'osnovno', null),
  ('secer',              'šećer',                 '{šećer u prahu,smeđi šećer}',                      true,  'osnovno', null),
  ('sol',                'sol',                   '{}',                                               true,  'začini', null),
  ('papar',              'papar',                 '{}',                                               true,  'začini', null),
  ('ulje',               'ulje',                  '{suncokretovo ulje,maslinovo ulje}',               true,  'masnoće', null),
  ('luk',                'luk',                   '{crveni luk,kapula}',                              true,  'povrće', 100),
  ('cesnjak',            'češnjak',               '{bijeli luk,češanj}',                              true,  'povrće', 5),
  ('krumpir',            'krumpir',               '{krompir}',                                        true,  'povrće', 150),
  ('riza',               'riža',                  '{}',                                               true,  'žitarice', null),
  ('kiselo_zelje',       'kiselo zelje',          '{kiseli kupus,listovi kiselog kupusa}',            true,  'povrće', null),
  ('rajcica',            'rajčica',               '{pasirana rajčica,koncentrat rajčice,paradajz}',   true,  'povrće', 100),
  ('mrkva',              'mrkva',                 '{}',                                               true,  'povrće', 80),
  ('tjestenina',         'tjestenina',            '{špageti,makaroni,penne}',                         true,  'tjestenina', null),
  ('prasak_za_pecivo',   'prašak za pecivo',      '{}',                                               true,  'osnovno', null),
  ('slatka_paprika',     'slatka paprika (začin)','{mljevena paprika}',                               true,  'začini', null),
  ('voda',               'voda',                  '{}',                                               true,  'osnovno', null),
  ('vanilin_secer',      'vanilin šećer',         '{}',                                               true,  'osnovno', null);

insert into substitution_rules (ingredient_slug, role, concept_id, prefer, ratio, notes_hr, rank) values
  -- mlijeko
  ('mlijeko', 'any',   'zobeno_mlijeko',  '{"zasladeno":"nezaslađeno","okus":"bez okusa"}', 1, 'Zobeni napitak bez šećera i okusa najbliži je mlijeku u slanim i slatkim jelima.', 1),
  ('mlijeko', 'any',   'sojino_mlijeko',  '{"zasladeno":"nezaslađeno","okus":"bez okusa"}', 1, 'Sojin napitak ima više bjelančevina, dobro veže tijesto.', 2),
  ('mlijeko', 'any',   'bademovo_mlijeko','{"zasladeno":"nezaslađeno"}',                    1, 'Lagan okus; slabije veže, bolji za slatka jela.', 3),
  ('mlijeko', 'sweet', 'zobeno_mlijeko',  '{"okus":"vanilija"}',                            1, 'U kolačima smije biti i aromatiziran napitak.', 1),
  -- maslac
  ('maslac', 'frying',  'biljno_ulje',     '{}',                         0.8, 'Za prženje i pirjanje maslac nije potreban: dovoljno je ulje (oko 20 % manje).', 1),
  ('maslac', 'frying',  'kokosovo_ulje',   '{}',                         0.8, 'Kokosovo ulje podnosi visoke temperature, ali daje blag okus kokosa.', 2),
  ('maslac', 'flavour', 'veganski_maslac', '{"namjena":"za mazanje"}',   1,   'Kad je maslac nositelj okusa (pire, umaci), biljni maslac 1:1.', 1),
  ('maslac', 'baking',  'veganski_maslac', '{"namjena":"za pečenje"}',   1,   'Za tijesta biljni blok za pečenje 1:1 zadržava strukturu.', 1),
  ('maslac', 'baking',  'kokosovo_ulje',   '{}',                         0.8, 'Kokosovo ulje u tijestima, oko 20 % manje.', 2),
  ('maslac', 'any',     'veganski_maslac', '{}',                         1,   'Biljni maslac 1:1.', 1),
  ('maslac', 'any',     'biljno_ulje',     '{}',                         0.8, 'Ulje kad maslac služi samo kao masnoća.', 2),
  -- vrhnja i jogurt
  ('vrhnje_za_kuhanje', 'any', 'biljno_vrhnje_za_kuhanje', '{"namjena":"za kuhanje"}', 1, 'Biljno vrhnje za kuhanje ne zgrušava se na vatri.', 1),
  ('slatko_vrhnje',     'any', 'biljno_vrhnje_za_kuhanje', '{}',                      1, 'Za umake; za šlag je potrebno kokosovo vrhnje za tučenje.', 1),
  ('kiselo_vrhnje',     'any', 'biljno_kiselo_vrhnje',     '{}',                      1, 'Biljna alternativa kiselom vrhnju 1:1.', 1),
  ('kiselo_vrhnje',     'any', 'biljni_jogurt',            '{"zasladeno":"nezaslađeno"}', 1, 'Nezaslađeni biljni jogurt s kapljicom limuna.', 2),
  ('mileram',           'any', 'biljno_kiselo_vrhnje',     '{}',                      1, 'Biljna alternativa kiselom vrhnju 1:1.', 1),
  ('mileram',           'any', 'biljni_jogurt',            '{"zasladeno":"nezaslađeno"}', 1, 'Biljni jogurt za lakšu varijantu.', 2),
  ('jogurt',            'any', 'biljni_jogurt',            '{"zasladeno":"nezaslađeno"}', 1, 'Biljni jogurt 1:1.', 1),
  -- sirevi
  ('sir',        'any', 'veganski_sir',       '{}',                      1,   'Biljni sir na bazi kokosa topi se slično.', 1),
  ('sir',        'any', 'prehrambeni_kvasac', '{}',                      0.3, 'Prehrambeni kvasac daje sirast okus bez masnoće.', 2),
  ('parmezan',   'any', 'veganski_sir',       '{"oblik":"blok"}',        1,   'Biljni "parmezan" za ribanje.', 1),
  ('parmezan',   'any', 'prehrambeni_kvasac', '{}',                      0.5, 'Prehrambeni kvasac je klasična veganska zamjena za parmezan.', 2),
  ('mozzarella', 'any', 'veganski_sir',       '{"oblik":"ribano"}',      1,   'Ribani biljni sir za pizzu i zapečena jela.', 1),
  ('svjezi_sir', 'any', 'tofu',               '{"okus":"bez okusa"}',    1,   'Izmrvljeni tofu natur s malo biljnog jogurta i limuna ima teksturu svježeg sira.', 1),
  ('svjezi_sir', 'any', 'biljni_jogurt',      '{"zasladeno":"nezaslađeno"}', 0.5, 'Za kremastiji nadjev dodaj biljni jogurt.', 2),
  ('krem_sir',   'any', 'biljno_kiselo_vrhnje','{}',                     1,   'Gusta biljna krema kao namaz.', 1),
  -- jaja
  ('jaje', 'binder',    'laneno_sjeme',    '{}',                 0.18, '1 jaje = 1 žlica mljevenog lana + 3 žlice vode, odstajati 5 min.', 1),
  ('jaje', 'binder',    'zamjena_za_jaja', '{}',                 0.18, 'Gotova zamjena za jaja, prema uputi na pakiranju.', 2),
  ('jaje', 'leavening', 'zamjena_za_jaja', '{}',                 0.18, 'Za dizanje: zamjena za jaja + malo više praška za pecivo.', 1),
  ('jaje', 'leavening', 'laneno_sjeme',    '{}',                 0.18, 'Lan veže, ali slabije diže; dodaj prašak za pecivo.', 2),
  ('jaje', 'base',      'tofu',            '{"okus":"bez okusa"}', 1,  'Za kajganu i omlet: izmrvljeni tofu s kurkumom i crnom soli.', 1),
  ('jaje', 'any',       'zamjena_za_jaja', '{}',                 0.18, 'Gotova zamjena za jaja.', 1),
  ('jaje', 'any',       'laneno_sjeme',    '{}',                 0.18, '1 jaje = 1 žlica mljevenog lana + 3 žlice vode.', 2),
  -- meso
  ('mljeveno_meso', 'any',   'mljevena_biljna_zamjena', '{}',                   1,    'Biljno mljeveno 1:1, ne treba ga dugo pirjati.', 1),
  ('mljeveno_meso', 'any',   'sojine_ljuskice',         '{}',                   0.35, 'Suhe sojine ljuskice namočene u temeljcu: 100 g suhih ≈ 300 g mesa.', 2),
  ('panceta',       'smoky', 'tofu',                    '{"okus":"dimljeno"}',  1,    'Dimljeni tofu na kockice daje dimljeni okus pancete.', 1),
  ('panceta',       'smoky', 'veganske_kobasice',       '{"okus":"dimljeno"}',  1,    'Dimljene veganske kobasice kao alternativa.', 2),
  ('panceta',       'any',   'tofu',                    '{"okus":"dimljeno"}',  1,    'Dimljeni tofu na kockice.', 1),
  ('slanina',       'any',   'tofu',                    '{"okus":"dimljeno"}',  1,    'Dimljeni tofu na tanke trakice, zapržen.', 1),
  ('slanina',       'any',   'veganske_kobasice',       '{"okus":"dimljeno"}',  1,    'Dimljene veganske kobasice.', 2),
  ('suho_meso',     'any',   'tofu',                    '{"okus":"dimljeno"}',  1,    'Dimljeni tofu nosi dimljeni okus u varivima i sarmi.', 1),
  ('suho_meso',     'any',   'veganske_kobasice',       '{"okus":"dimljeno"}',  1,    'Dimljene veganske kobasice.', 2),
  ('kobasica',      'any',   'veganske_kobasice',       '{}',                   1,    'Veganske kobasice 1:1.', 1),
  ('kobasica',      'any',   'tofu',                    '{"okus":"dimljeno"}',  1,    'Dimljeni tofu u komadima.', 2),
  ('sunka',         'any',   'tofu',                    '{"okus":"dimljeno"}',  1,    'Dimljeni tofu narezan na tanko.', 1),
  ('piletina',      'any',   'tofu',                    '{"okus":"bez okusa"}', 1,    'Tofu natur, prešan i mariniran.', 1),
  ('piletina',      'any',   'sojine_ljuskice',         '{}',                   0.35, 'Krupni sojin granulat namočen u temeljcu.', 2),
  ('svinjska_mast', 'any',   'biljno_ulje',             '{}',                   0.9,  'Ulje umjesto masti za prženje i dinstanje.', 1),
  ('svinjska_mast', 'baking','veganski_maslac',         '{"namjena":"za pečenje"}', 1, 'Biljni blok za pečenje u tijestima.', 1),
  -- ostalo
  ('med',                 'any', 'agavin_sirup',        '{}', 1, 'Agavin sirup 1:1, malo je slađi.', 1),
  ('tjestenina_s_jajima', 'any', 'tjestenina_bez_jaja', '{}', 1, 'Većina suhe tjestenine (durum) je bez jaja.', 1),
  ('majoneza',            'any', 'veganska_majoneza',   '{}', 1, 'Veganska majoneza 1:1.', 1);
